name: Auto Merge 

on:
  push:
    branches:
      - dev

jobs:
  automerge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Enable auto-merge
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        merge-method: squash
        commit-message: 'Auto-merge pull request #${{ github.event.pull_request.number }}'

    # Add any additional steps you may need after the merge if necessary

