name: Automated Pull Request ana Merge

on:
  push:
    branches:
      - dev

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Automated pull request
        title: Automated Pull Request
        body: |
          This is an automated pull request created upon pushing changes to the dev branch.
        base: master  # The branch where changes will be merged
        head: dev   # The branch from which changes are pushed
        
  automerge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Enable auto-merge
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        merge-method: squash
        commit-message: 'Auto-merge pull request #${{ github.event.pull_request.number }}'
