name: Automated Pull Request

on:
  push:
    branches:
      - dev

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PAT }}
        commit-message: Automated pull request
        title: Automated Pull Request
        body: |
          This is an automated pull request created upon pushing changes to the dev branch.
        branch: dev
